spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: 2458
  jpa:
    hibernate:
      ddl-auto: update

cloud:
  aws:
    credentials:
      access-key: accessKey
      secret-key: secretKey
    region:
      static: eu-north-1

application:
  bucket:
    name: bucket-for-streaming-service