spring:
  datasource:
    url: jdbc:h2:mem:webapp
    username: user
    password: user
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true